apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ey3ynumad-python-gitops
  description: This is GitOps manifest for ey3ynumad-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ey3ynumad-python
    backstage.io/kubernetes-id: ey3ynumad-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ey3ynumad-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ey3ynumad-python
