apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ey3ynumad-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ey3ynumad-python 
  name: ey3ynumad-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ey3ynumad-python 
